name: Run Python Script

on:
  workflow_dispatch:
    inputs:
      ip-addresses:
        description: 'Enter a comma-separated list of IP addresses to scan'
        required: true

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install impacket
        run: python -m pip install pytube 
      - name: Install vlc
        run: sudo snap install vlc

      - name: Run Python script
        run: python yt.py 
